spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/demo_application?useSSL=false
spring.datasource.username=root
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=update

