spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/demo_application?useSSL=false
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=Munnish@96
=======
spring.datasource.password=rootroot@1
>>>>>>> origin/master
spring.jpa.hibernate.ddl-auto=update

